from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('agile_led', src, depend = ['PKG_AGILE_LED_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
